#include <ncurses.h>

#define COLORSTATE_DEFAULT 1
#define BG_DEFAULT COLOR_WHITE
#define AXES_DEFAULT COLOR_BLACK
#define CURVE1_DEFAULT COLOR_RED
#define CURVE2_DEFAULT COLOR_GREEN
#define CURVE3_DEFAULT COLOR_BLUE
